services:
  - type: web
    name: aura-vision-assistant
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    plan: free
    envVars:
      - key: NODE_VERSION
        value: "20.11.0"
      - key: GOOGLE_AI_API_KEY
        sync: false
      - key: GOOGLE_CLOUD_API_KEY
        sync: false 