services:
  - type: web
    name: aura-vision-assistant
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: GOOGLE_AI_API_KEY
        sync: false
      - key: GOOGLE_CLOUD_API_KEY
        sync: false 